import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'tr' | 'en';

interface Translations {
  [key: string]: string;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Translations> = {
  tr: {
    // Customer
    'customer.title': 'Lezzetli',
    'customer.subtitle': 'Deneyimler',
    'customer.description': 'Şehrin en iyi restoranlarını keşfedin, rezervasyon yapın ve unutulmaz lezzet deneyimleri yaşayın.',
    'customer.startExploring': 'Keşfetmeye Başla',
    'customer.signIn': 'Giriş Yap',
    'customer.nearbyRestaurants': 'Yakındaki Restoranlar',
    'customer.nearbyDesc': 'Konumunuza yakın en iyi restoranları keşfedin',
    'customer.realReviews': 'Gerçek Yorumlar',
    'customer.realReviewsDesc': 'Diğer müşterilerin gerçek deneyimlerini okuyun',
    'customer.quickOrder': 'Hızlı Sipariş',
    'customer.quickOrderDesc': 'QR kod ile anında menüye erişin ve sipariş verin',
    
    // Common
    'common.save': 'Kaydet',
    'common.cancel': 'İptal',
    'common.delete': 'Sil',
    'common.edit': 'Düzenle',
    'common.add': 'Ekle',
    'common.search': 'Ara',
    'common.close': 'Kapat',
    'common.loading': 'Yükleniyor...',
    'common.yes': 'Evet',
    'common.no': 'Hayır',
    'common.or': 'veya',
    'common.ok': 'Tamam',
    'common.demo': 'Demo',
    'common.all': 'Tümü',
    'common.popular': 'Popüler',
    'common.inStock': 'Stokta',
    'common.outOfStock': 'Tükendi',
    'common.comments': 'yorum',
    'common.comment': 'Yorum',
    'common.description': 'Açıklama',
    'common.price': 'Fiyat',
    'common.total': 'Toplam',
    'common.subtotal': 'Ara Toplam',
    'common.table': 'Masa',
    'common.persons': 'Kişilik',
    'common.capacity': 'Kapasite',
    'common.available': 'Müsait',
    'common.occupied': 'Dolu',
    'common.reserved': 'Rezerve',
    'common.pending': 'Beklemede',
    'common.preparing': 'Hazırlanıyor',
    'common.ready': 'Hazır',
    'common.served': 'Servis Edildi',
    'common.completed': 'Tamamlandı',
    'common.cancelled': 'İptal Edildi',
    'common.details': 'Detaylar',
    'common.share': 'Paylaş',
    'common.download': 'İndir',
    'common.liked': 'Beğenildi',
    'common.like': 'Beğen',
    'common.views': 'Görüntülenme',
    'common.likes': 'Beğeni',
    
    // Login
    'login.title': 'Giriş Yapın',
    'login.welcome': 'Lezzet dünyasına hoş geldiniz',
    'login.email': 'E-posta',
    'login.password': 'Şifre',
    'login.loginButton': 'Giriş Yap',
    'login.googleLogin': 'Google ile Giriş Yap',
    'login.noAccount': 'Hesabınız yok mu?',
    'login.register': 'Kayıt Olun',
    'login.demo': 'Demo: Herhangi bir butona tıklayarak uygulamayı keşfedebilirsiniz',
    'login.emailPlaceholder': 'ornek@email.com',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Hoş Geldiniz',
    'dashboard.todayOrders': 'Bugünkü Siparişler',
    'dashboard.dailyRevenue': 'Günlük Gelir',
    'dashboard.weeklyOrders': 'Haftalık Sipariş Grafiği',
    'dashboard.tableStatus': 'Masa Durumu',
    'dashboard.recentOrders': 'Son Siparişler',
    'dashboard.viewAll': 'Tümünü Gör',
    'dashboard.stats': 'İstatistikler',
    'dashboard.activeTables': 'Aktif Masalar',
    'dashboard.satisfaction': 'Memnuniyet',
    'dashboard.last7days': 'Son 7 Gün',
    'dashboard.liveView': 'Canlı Görünüm',
    'dashboard.todaysOrders': 'Bugünün Siparişleri',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.tables': 'Masalar',
    'nav.menu': 'Menü',
    'nav.orders': 'Siparişler',
    'nav.campaigns': 'Kampanyalar',
    'nav.loyalty': 'Sadakat',
    'nav.marketing': 'Pazarlama',
    'nav.reservations': 'Rezervasyonlar',
    'nav.settings': 'Ayarlar',
    'nav.logout': 'Çıkış Yap',
    'nav.explore': 'Keşfet',
    'nav.shorts': 'Shorts',
    'nav.takeaway': 'Gel-Al',
    'nav.profile': 'Profil',
    
    // Tables
    'tables.title': 'Masa Yönetimi',
    'tables.subtitle': 'Masalarınızı yönetin ve QR kodlarını görüntüleyin',
    'tables.addNew': 'Yeni Masa Ekle',
    'tables.totalTables': 'Toplam Masa',
    'tables.scan': 'QR Kodu Tarayın',
    'tables.viewQR': 'QR Kodu Görüntüle',
    'tables.tableNumber': 'Masa Numarası',
    'tables.numberPlaceholder': 'Örn: 7',
    'tables.capacitySelect': 'Kapasite seçin',
    'tables.qrTitle': 'QR Kodu',
    'tables.qrMessage': 'Bu QR kodu masanıza yerleştirin. Müşteriler bu kodu tarayarak dijital menüye ulaşabilir.',
    'tables.table': 'Masa',
    'tables.persons': 'Kişilik',
    'tables.available': 'Müsait',
    'tables.occupied': 'Dolu',
    'tables.reserved': 'Rezerve',
    
    // Menu
    'menu.title': 'Menü Yönetimi',
    'menu.subtitle': 'Menü öğelerinizi ekleyin, düzenleyin ve yönetin',
    'menu.addNew': 'Yeni Ürün Ekle',
    'menu.productName': 'Ürün Adı',
    'menu.productNamePlaceholder': 'Örn: Margherita Pizza',
    'menu.category': 'Kategori',
    'menu.categorySelect': 'Kategori seçin',
    'menu.descriptionPlaceholder': 'Ürün açıklaması...',
    'menu.calories': 'Kalori',
    'menu.preparationTime': 'Hazırlama Süresi (dk)',
    'menu.imageUrl': 'Resim URL',
    'menu.videoUrl': 'Video URL (Opsiyonel)',
    'menu.ingredients': 'İçindekiler (Her satıra bir malzeme)',
    'menu.allergens': 'Alerjenler (Virgülle ayırın)',
    'menu.hasVideo': 'Video var',
    'menu.hasImage': 'Resim',
    'menu.kcal': 'kcal',
    'menu.min': 'dk',
    
    // Orders
    'orders.title': 'Sipariş Yönetimi',
    'orders.subtitle': 'Gelen siparişleri yönetin ve durumlarını güncelleyin',
    'orders.totalOrders': 'Toplam Sipariş',
    'orders.orderDetail': 'Sipariş Detayı',
    'orders.orderNumber': 'Sipariş #',
    'orders.note': 'Not:',
    'orders.startPreparing': 'Hazırlamaya Başla',
    'orders.markReady': 'Hazır',
    'orders.preparing': 'Hazırlanıyor',
    'orders.completed': 'Tamamlandı',
    'orders.pending': 'Beklemede',
    
    // Reservation
    'reservation.title': 'Rezervasyon Yap',
    'reservation.features': 'Özellikler',
    'reservation.selectDateTime': 'Tarih ve Saat Seçin',
    'reservation.selectDate': 'Tarih Seçin',
    'reservation.selectTime': 'Saat Seçin',
    'reservation.partySize': 'Kişi Sayısı',
    'reservation.selectTable': 'Masa Seçin',
    'reservation.tableSelectionNote': 'Uygun masaları seçebilirsiniz',
    'reservation.customerInfo': 'İletişim Bilgileri',
    'reservation.customerName': 'Ad Soyad',
    'reservation.namePlaceholder': 'Adınız ve soyadınız',
    'reservation.phone': 'Telefon',
    'reservation.email': 'E-posta',
    'reservation.specialRequests': 'Özel İstekler',
    'reservation.requestsPlaceholder': 'Doğum günü kutlaması, alerji bilgileri vb.',
    'reservation.confirmReservation': 'Rezervasyonu Onaylayın',
    'reservation.restaurant': 'Restoran',
    'reservation.date': 'Tarih',
    'reservation.time': 'Saat',
    'reservation.reservationFee': 'Rezervasyon Ücreti',
    'reservation.feeDescription': 'Bu ücret hesaptan düşülecektir',
    'reservation.proceedToPayment': 'Ödemeye Geç',
    'reservation.payment': 'Ödeme',
    'reservation.paymentSummary': 'Ödeme Özeti',
    'reservation.paymentMethod': 'Ödeme Yöntemi',
    'reservation.creditCard': 'Kredi Kartı',
    'reservation.feeRefundInfo': 'Rezervasyon Ücreti Bilgisi',
    'reservation.feeRefundDescription': 'Rezervasyon ücreti hesabınızdan düşülecek ve hesap ödendiğinde geri iade edilecektir.',
    'reservation.payAndReserve': 'Öde ve Rezervasyon Yap',
    
    // Reservations (Dashboard)
    'reservations.title': 'Rezervasyon Yönetimi',
    'reservations.subtitle': 'Rezervasyonları yönetin ve durumlarını güncelleyin',
    'reservations.totalReservations': 'Toplam Rezervasyon',
    'reservations.pendingReservations': 'Bekleyen Rezervasyonlar',
    'reservations.confirmedReservations': 'Onaylanan Rezervasyonlar',
    'reservations.reservationRevenue': 'Rezervasyon Geliri',
    'reservations.searchPlaceholder': 'Müşteri adı, telefon veya masa ara...',
    'reservations.allStatus': 'Tüm Durumlar',
    'reservations.pending': 'Beklemede',
    'reservations.confirmed': 'Onaylandı',
    'reservations.completed': 'Tamamlandı',
    'reservations.cancelled': 'İptal Edildi',
    'reservations.noShow': 'Gelmedi',
    'reservations.confirm': 'Onayla',
    'reservations.cancel': 'İptal Et',
    'reservations.markCompleted': 'Tamamla',
    'reservations.reservationDetails': 'Rezervasyon Detayları',
    'reservations.customerName': 'Müşteri Adı',
    'reservations.phone': 'Telefon',
    'reservations.email': 'E-posta',
    'reservations.partySize': 'Kişi Sayısı',
    'reservations.table': 'Masa',
    'reservations.dateTime': 'Tarih ve Saat',
    'reservations.notes': 'Notlar',
    'reservations.noReservations': 'Rezervasyon Bulunamadı',
    'reservations.noReservationsMessage': 'Bu tarihte henüz rezervasyon bulunmamaktadır.',
    'orders.markServed': 'Servis Edildi',
    'orders.cancelOrder': 'İptal Et',
    'orders.noOrders': 'Sipariş Bulunamadı',
    'orders.noOrdersMessage': 'Bu durumda henüz sipariş bulunmamaktadır.',
    
    // Campaigns
    'campaigns.title': 'Kampanya Yönetimi',
    'campaigns.subtitle': 'İndirimler ve promosyonlarınızı yönetin',
    'campaigns.addNew': 'Yeni Kampanya Ekle',
    'campaigns.activeCampaigns': 'Aktif Kampanya',
    'campaigns.thisMonthUsage': 'Bu Ay Kullanım',
    'campaigns.totalDiscount': 'Toplam İndirim',
    'campaigns.bogo': '2 AL 1 ÖDE',
    'campaigns.validUntil': 'Geçerlilik:',
    'campaigns.campaignTitle': 'Kampanya Başlığı',
    'campaigns.titlePlaceholder': 'Örn: Hafta Sonu İndirimi',
    'campaigns.descriptionPlaceholder': 'Kampanya detayları...',
    'campaigns.campaignType': 'Kampanya Tipi',
    'campaigns.percentageDiscount': 'Yüzde İndirim',
    'campaigns.fixedDiscount': 'Sabit İndirim',
    'campaigns.bogoFull': '2 Al 1 Öde',
    'campaigns.typeSelect': 'Tip seçin',
    'campaigns.discountAmount': 'İndirim Miktarı',
    'campaigns.endDate': 'Bitiş Tarihi',
    'campaigns.bannerUrl': 'Görsel URL',
    
    // Loyalty
    'loyalty.title': 'Sadakat Programı',
    'loyalty.subtitle': 'Müşteri sadakatini artıracak ödüller oluşturun',
    'loyalty.programMembers': 'Program Üyesi',
    'loyalty.thisMonthRewards': 'Bu Ay Kullanılan Ödül',
    'loyalty.activeUsers': 'Aktif Kullanıcı',
    'loyalty.programDetails': 'Sadakat programı detayları',
    'loyalty.earnPoints': 'Her ₺1 harcamaya {points} puan kazanın!',
    'loyalty.collectPoints': 'Puanlarınızı toplayın ve özel ödüllerinizi kazanın',
    'loyalty.rewards': 'Ödüller',
    'loyalty.addReward': 'Yeni Ödül Ekle',
    'loyalty.points': 'Puan',
    'loyalty.recentRedemptions': 'Son Kullanılan Ödüller',
    'loyalty.last7Days': 'Son 7 gün',
    'loyalty.rewardName': 'Ödül Adı',
    'loyalty.rewardNamePlaceholder': 'Örn: Ücretsiz Tatlı',
    'loyalty.rewardDescription': 'Ödül detayları...',
    'loyalty.requiredPoints': 'Gereken Puan',
    
    // Marketing
    'marketing.title': 'Pazarlama & Reklam',
    'marketing.subtitle': 'Shorts videoları ve banner reklamları yönetin',
    'marketing.shortsVideos': 'Shorts Videoları',
    'marketing.totalViews': 'Toplam Görüntülenme',
    'marketing.totalLikes': 'Toplam Beğeni',
    'marketing.bannerAds': 'Banner Reklamları',
    'marketing.addVideo': 'Yeni Video Ekle',
    'marketing.addBanner': 'Yeni Banner Ekle',
    'marketing.videoTitle': 'Video Başlığı',
    'marketing.videoTitlePlaceholder': 'Örn: Yeni Pizza Tarifimiz',
    'marketing.videoUrl': 'Video URL',
    'marketing.thumbnailUrl': 'Thumbnail URL',
    'marketing.bannerTitle': 'Banner Başlığı',
    'marketing.bannerTitlePlaceholder': 'Örn: Özel Teklif',
    'marketing.bannerImageUrl': 'Banner Görsel URL',
    
    // Settings
    'settings.title': 'Restoran Ayarları',
    'settings.subtitle': 'Restoran bilgilerinizi ve özelliklerinizi yönetin',
    'settings.basicInfo': 'Temel Bilgiler',
    'settings.restaurantName': 'Restoran Adı',
    'settings.cuisine': 'Mutfak Türü',
    'settings.priceRange': 'Fiyat Aralığı',
    'settings.economical': '₺ - Ekonomik',
    'settings.medium': '₺₺ - Orta',
    'settings.expensive': '₺₺₺ - Pahalı',
    'settings.luxury': '₺₺₺₺ - Lüks',
    'settings.location': 'Konum Bilgileri',
    'settings.address': 'Adres',
    'settings.city': 'İl',
    'settings.district': 'İlçe',
    'settings.workingHours': 'Çalışma Saatleri',
    'settings.openingTime': 'Açılış',
    'settings.closingTime': 'Kapanış',
    'settings.features': 'Mekan Özellikleri',
    'settings.featuresSubtitle': 'Restoranınızın özelliklerini seçin',
    'settings.saveChanges': 'Değişiklikleri Kaydet',
    'settings.preview': 'Ön İzleme',
    'settings.statistics': 'İstatistikler',
    'settings.totalReviews': 'Toplam Değerlendirme',
    'settings.averageRating': 'Ortalama Puan',
    'settings.menuItems': 'Menü Öğesi',
    'settings.tableCount': 'Masa Sayısı',
    
    // Customer App - Explore
    'explore.search': 'Restoran veya mutfak ara...',
    'explore.featured': 'Bölgenin Yıldızları',
    'explore.featuredBadge': 'Öne Çıkan',
    'explore.allRestaurants': 'Tüm Restoranlar',
    'explore.tablesAvailable': 'masa müsait',
    'explore.capacity': 'kişilik',
    'explore.avgTime': 'Ort. 15 dk',
    
    // Customer App - Shorts
    'shorts.title': 'Shorts',
    'shorts.subtitle': 'Restoranlardan özel içerikler ve kampanyalar',
    'shorts.restaurant': 'Restoran',
    'shorts.noComments': 'Henüz yorum yapılmamış',
    
    // Customer App - Restaurant Detail
    'restaurant.notFound': 'Restoran bulunamadı',
    'restaurant.menu': 'Menü',
    'restaurant.reviews': 'Yorumlar',
    'restaurant.campaigns': 'Kampanyalar',
    'restaurant.info': 'Bilgiler',
    'restaurant.workingHours': 'Çalışma Saatleri',
    'restaurant.loyaltyProgram': 'Sadakat Programı',
    'restaurant.earnPerLira': 'Her ₺1\'e {points} puan',
    'restaurant.joinProgram': 'Programa Katıl',
    'restaurant.takeaway': 'Gel-Al Sipariş Ver',
    'restaurant.makeReservation': 'Rezervasyon Yap',
    'restaurant.ambiance': 'Ambiyans:',
    'restaurant.hygiene': 'Hijyen:',
    'restaurant.service': 'Hizmet:',
    
    // Customer App - Takeaway
    'takeaway.title': 'Gel-Al Sipariş',
    'takeaway.subtitle': 'Siparişinizi verin, restorana gidip teslim alın',
    'takeaway.selectRestaurant': 'Restoran Seçin',
    'takeaway.myCart': 'Sepetim',
    'takeaway.emptyCart': 'Sepetiniz boş',
    'takeaway.backToMenu': 'Menüye Dön',
    'takeaway.addToCart': 'Ekle',
    'takeaway.yourOrder': 'Siparişiniz',
    'takeaway.orderNote': 'Sipariş Notu (Opsiyonel)',
    'takeaway.notePlaceholder': 'Örn: Az pişmiş pizza istiyorum',
    'takeaway.paymentSummary': 'Ödeme Özeti',
    'takeaway.serviceFee': 'Servis Ücreti (%10)',
    'takeaway.proceedToPayment': 'Ödemeye Geç',
    'takeaway.completeOrder': 'Siparişi Tamamla',
    'takeaway.orderReceived': 'Sipariş Alındı!',
    'takeaway.orderReceivedMessage': 'Siparişiniz Alındı!',
    'takeaway.orderNumber': 'Sipariş numaranız: #{number}',
    'takeaway.pickupMessage': 'Siparişiniz hazırlanıyor. Lütfen 15-20 dakika içinde restorana gelerek fiş numaranızı göstererek siparişinizi alın.',
    'takeaway.orderSummary': 'Sipariş Özeti',
    'takeaway.restaurant': 'Restoran:',
    'takeaway.estimatedTime': 'Tahmini Hazırlık Süresi: 15-20 dakika',
    'takeaway.confirmOrder': 'Siparişi Onayla',
    
    // Customer App - Profile
    'profile.memberSince': 'Üye: {year}',
    'profile.editProfile': 'Profili Düzenle',
    'profile.stats': 'İstatistikler',
    'profile.totalOrders': 'Toplam Sipariş',
    'profile.favoriteRestaurants': 'Favori Restoran',
    'profile.reviewCount': 'Yorum Sayısı',
    'profile.totalPoints': 'Toplam Puan',
    'profile.loyaltyPrograms': 'Sadakat Programları',
    'profile.pointStatus': 'Puan durumunuz',
    'profile.recentOrders': 'Son Siparişler',
    'profile.orderHistory': 'Geçmiş siparişleriniz',
    'profile.viewAllOrders': 'Tüm Siparişleri Gör',
    'profile.myReviews': 'Yorumlarım',
    'profile.reviewsSubtitle': 'Yaptığınız değerlendirmeler',
    
    // QR Menu
    'qr.digitalMenu': 'Dijital Menü',
    'qr.callWaiter': 'Garson Çağır',
    'qr.cart': 'Sepet',
    'qr.popularItems': 'Popüler Ürünler',
    'qr.preparation': 'Hazırlık',
    'qr.ingredients': 'İçindekiler',
    'qr.allergenWarning': 'Alerjen Uyarısı',
    'qr.watchVideo': 'Yapılış Videosunu İzle',
    'qr.addToCart': 'Sepete Ekle',
    'qr.notInStock': 'Stokta Yok',
    'qr.waiterCalled': 'Garson çağrıldı',
    'qr.goToCart': 'Sepete Git',
    'qr.items': 'Ürün',
    'qr.myCart': 'Sepetim',
    'qr.payment': 'Ödeme',
    'qr.paymentMethod': 'Ödeme Yöntemi',
    'qr.creditCard': 'Kredi/Banka Kartı',
    'qr.cash': 'Nakit',
    'qr.tip': 'Bahşiş',
    'qr.noTip': 'Yok',
    'qr.tipAmount': 'Bahşiş tutarı:',
    'qr.pay': 'Ödeme Yap',
    'qr.processing': 'İşleniyor...',
    'qr.cashPaymentNote': 'Nakit Ödeme: Lütfen garsonunuza nakit olarak ödeme yapmak istediğinizi belirtin.',
    'qr.paymentSuccess': 'Ödeme Başarılı!',
    'qr.thankYou': 'Siparişiniz için teşekkür ederiz',
    'qr.orderNumber': 'Sipariş No',
    'qr.date': 'Tarih',
    'qr.time': 'Saat',
    'qr.product': 'Ürün',
    'qr.quantity': 'Adet',
    'qr.paymentMethodInfo': 'Ödeme Yöntemi',
    'qr.creditCardLast4': 'Kredi Kartı (**** {last4})',
    'qr.downloadReceipt': 'Fiş İndir',
    'qr.rateExperience': 'Deneyiminizi Değerlendirin',
    'qr.thankYouNote': 'Tekrar görüşmek dileğiyle, afiyet olsun! 🍽️',
    'qr.shareExperience': 'Deneyiminizi Paylaşın',
    'qr.overallRating': 'Genel Değerlendirme',
    'qr.excellent': 'Mükemmel! 🌟',
    'qr.veryGood': 'Çok iyi! 👍',
    'qr.good': 'İyi 😊',
    'qr.average': 'Orta 😐',
    'qr.poor': 'Kötü 😞',
    'qr.detailedRating': 'Detaylı Değerlendirme',
    'qr.ambiance': 'Ambiyans',
    'qr.hygiene': 'Hijyen',
    'qr.service': 'Hizmet',
    'qr.foodRating': 'Yemek Değerlendirmesi',
    'qr.yourComment': 'Yorumunuz (Opsiyonel)',
    'qr.commentPlaceholder': 'Deneyiminizi bizimle paylaşın...',
    'qr.submitReview': 'Değerlendirmeyi Gönder',
    'qr.notNow': 'Şimdi Değil',
    'qr.reviewThanks': 'Teşekkür Ederiz!',
    'qr.reviewSaved': 'Yorumunuz kaydedildi',
    'qr.reservationFeeDeduction': 'Rezervasyon Ücreti İndirimi',
    'qr.reservationFeeInfo': 'Rezervasyon Ücreti Bilgisi',
    'qr.reservationFeeDescription': 'Rezervasyon ücretiniz hesabınızdan düşülmüştür.',
    'qr.table': 'Masa',
    'qr.persons': 'Kişilik',
    'qr.item': 'Ürün',
    'qr.serviceFee': 'Servis Ücreti',
    'qr.paymentSummary': 'Ödeme Özeti',
    'qr.cashPayment': 'Nakit Ödeme',
    'qr.share': 'Paylaş',
    'qr.paymentSuccessful': 'Ödeme Başarılı',
    'qr.thankYouForOrder': 'Siparişiniz için teşekkür ederiz',
    'qr.backToMenu': 'Menüye Dön',
    'qr.openDemoMenu': 'Demo Menüyü Aç',
    'qr.scanQR': 'Masanızdaki QR kodu tarayın',
    'qr.howToUse': 'Nasıl Kullanılır?',
    'qr.step1': 'Masanızdaki QR kodu telefonunuzun kamerasıyla tarayın',
    'qr.step2': 'Dijital menümüzü inceleyin ve siparişinizi verin',
    'qr.step3': 'Ödemenizi yapın ve yemeğinizin keyfini çıkarın',
    'qr.demoMode': 'Demo Modu',
    'qr.demoDesc': 'Uygulamayı test etmek için demo menüyü açabilirsiniz',
    'qr.scanIssue': 'QR kod okutmakta sorun mu yaşıyorsunuz? Lütfen personelimizden yardım isteyin.',
    'qr.emptyCart': 'Sepetiniz boş',
    'qr.yourOrder': 'Siparişiniz',
    'qr.proceedToPayment': 'Ödemeye Geç',
    'qr.calories': 'Kalori',
    'qr.min': 'dk',
    'qr.outOfStock': 'Tükendi',
    'qr.orderNotes': 'Sipariş Notları',
    'qr.orderNotesPlaceholder': 'Özel istekleriniz varsa buraya yazabilirsiniz...',
    'qr.all': 'Tümü',
    'qr.goToCartWith': 'Sepete Git',
    'qr.vegan': 'Vegan',
    'qr.vegetarian': 'Vejetaryen',
    'qr.glutenFree': 'Glutensiz',
    
    // Home Page
    'home.restaurant': 'Restoran',
    'home.happyCustomer': 'Mutlu Müşteri',
    'home.avgRating': 'Ortalama Puan',
    'home.orders': 'Sipariş',
    'home.cuisineTurkish': 'Türk Mutfağı',
    'home.cuisineItalian': 'İtalyan',
    'home.cuisineJapanese': 'Japon',
    'home.cuisineChinese': 'Çin',
    'home.cuisineMexican': 'Meksika',
    'home.cuisineIndian': 'Hint',
    'home.popularCategories': 'Popüler Kategoriler',
    'home.whyChefPoint': 'Neden Chef Point?',
    'home.popularRestaurants': 'Popüler Restoranlar',
    'home.trendingRestaurants': 'Trend Restoranlar',
    'home.viewAll': 'Tümünü Gör',
    'home.startExploring': 'Hemen Keşfetmeye Başlayın!',
    'home.exploreDescription': 'Binlerce restoran arasından size en uygun olanı bulun ve anında sipariş verin.',
    'home.explore': 'Keşfet →',
    'home.reviews': 'değerlendirme',
    'home.deliveryTime': 'dk',
    'home.popular': 'Popüler',
    'home.new': 'Yeni',
    'common.back': 'Geri',
    'common.next': 'İleri',
    'common.reviews': 'Yorumlar',
  },
  en: {
    // Customer
    'customer.title': 'Delicious',
    'customer.subtitle': 'Experiences',
    'customer.description': 'Discover the best restaurants in the city, make reservations and experience unforgettable flavors.',
    'customer.startExploring': 'Start Exploring',
    'customer.signIn': 'Sign In',
    'customer.nearbyRestaurants': 'Nearby Restaurants',
    'customer.nearbyDesc': 'Discover the best restaurants near your location',
    'customer.realReviews': 'Real Reviews',
    'customer.realReviewsDesc': 'Read real experiences from other customers',
    'customer.quickOrder': 'Quick Order',
    'customer.quickOrderDesc': 'Access menu instantly with QR code and place orders',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.or': 'or',
    'common.ok': 'OK',
    'common.demo': 'Demo',
    'common.all': 'All',
    'common.popular': 'Popular',
    'common.inStock': 'In Stock',
    'common.outOfStock': 'Out of Stock',
    'common.comments': 'reviews',
    'common.comment': 'Comment',
    'common.description': 'Description',
    'common.price': 'Price',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.table': 'Table',
    'common.persons': 'Persons',
    'common.capacity': 'Capacity',
    'common.available': 'Available',
    'common.occupied': 'Occupied',
    'common.reserved': 'Reserved',
    'common.pending': 'Pending',
    'common.preparing': 'Preparing',
    'common.ready': 'Ready',
    'common.served': 'Served',
    'common.completed': 'Completed',
    'common.cancelled': 'Cancelled',
    'common.details': 'Details',
    'common.share': 'Share',
    'common.download': 'Download',
    'common.liked': 'Liked',
    'common.like': 'Like',
    'common.views': 'Views',
    'common.likes': 'Likes',
    
    // Login
    'login.title': 'Sign In',
    'login.welcome': 'Welcome to the world of flavors',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.loginButton': 'Sign In',
    'login.googleLogin': 'Sign in with Google',
    'login.noAccount': "Don't have an account?",
    'login.register': 'Sign Up',
    'login.demo': 'Demo: Click any button to explore the application',
    'login.emailPlaceholder': 'example@email.com',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.todayOrders': "Today's Orders",
    'dashboard.dailyRevenue': 'Daily Revenue',
    'dashboard.weeklyOrders': 'Weekly Orders Chart',
    'dashboard.tableStatus': 'Table Status',
    'dashboard.recentOrders': 'Recent Orders',
    'dashboard.viewAll': 'View All',
    'dashboard.stats': 'Statistics',
    'dashboard.activeTables': 'Active Tables',
    'dashboard.satisfaction': 'Satisfaction',
    'dashboard.last7days': 'Last 7 Days',
    'dashboard.liveView': 'Live View',
    'dashboard.todaysOrders': "Today's Orders",
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.tables': 'Tables',
    'nav.menu': 'Menu',
    'nav.orders': 'Orders',
    'nav.campaigns': 'Campaigns',
    'nav.loyalty': 'Loyalty',
    'nav.marketing': 'Marketing',
    'nav.reservations': 'Reservations',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.explore': 'Explore',
    'nav.shorts': 'Shorts',
    'nav.takeaway': 'Takeaway',
    'nav.profile': 'Profile',
    
    // Tables
    'tables.title': 'Table Management',
    'tables.subtitle': 'Manage your tables and view QR codes',
    'tables.addNew': 'Add New Table',
    'tables.totalTables': 'Total Tables',
    'tables.scan': 'Scan QR Code',
    'tables.viewQR': 'View QR Code',
    'tables.tableNumber': 'Table Number',
    'tables.numberPlaceholder': 'e.g., 7',
    'tables.capacitySelect': 'Select capacity',
    'tables.qrTitle': 'QR Code',
    'tables.qrMessage': 'Place this QR code on your table. Customers can access the digital menu by scanning this code.',
    'tables.table': 'Table',
    'tables.persons': 'Persons',
    'tables.available': 'Available',
    'tables.occupied': 'Occupied',
    'tables.reserved': 'Reserved',
    
    // Menu
    'menu.title': 'Menu Management',
    'menu.subtitle': 'Add, edit and manage your menu items',
    'menu.addNew': 'Add New Item',
    'menu.productName': 'Product Name',
    'menu.productNamePlaceholder': 'e.g., Margherita Pizza',
    'menu.category': 'Category',
    'menu.categorySelect': 'Select category',
    'menu.descriptionPlaceholder': 'Product description...',
    'menu.calories': 'Calories',
    'menu.preparationTime': 'Preparation Time (min)',
    'menu.imageUrl': 'Image URL',
    'menu.videoUrl': 'Video URL (Optional)',
    'menu.ingredients': 'Ingredients (One per line)',
    'menu.allergens': 'Allergens (Comma separated)',
    'menu.hasVideo': 'Has Video',
    'menu.hasImage': 'Image',
    'menu.kcal': 'kcal',
    'menu.min': 'min',
    
    // Orders
    'orders.title': 'Order Management',
    'orders.subtitle': 'Manage incoming orders and update their status',
    'orders.totalOrders': 'Total Orders',
    'orders.orderDetail': 'Order Details',
    'orders.orderNumber': 'Order #',
    'orders.note': 'Note:',
    'orders.startPreparing': 'Start Preparing',
    'orders.markReady': 'Mark Ready',
    'orders.preparing': 'Preparing',
    'orders.completed': 'Completed',
    'orders.pending': 'Pending',
    
    // Reservation
    'reservation.title': 'Make Reservation',
    'reservation.features': 'Features',
    'reservation.selectDateTime': 'Select Date & Time',
    'reservation.selectDate': 'Select Date',
    'reservation.selectTime': 'Select Time',
    'reservation.partySize': 'Party Size',
    'reservation.selectTable': 'Select Table',
    'reservation.tableSelectionNote': 'You can select from available tables',
    'reservation.customerInfo': 'Contact Information',
    'reservation.customerName': 'Full Name',
    'reservation.namePlaceholder': 'Your full name',
    'reservation.phone': 'Phone',
    'reservation.email': 'Email',
    'reservation.specialRequests': 'Special Requests',
    'reservation.requestsPlaceholder': 'Birthday celebration, allergy information, etc.',
    'reservation.confirmReservation': 'Confirm Reservation',
    'reservation.restaurant': 'Restaurant',
    'reservation.date': 'Date',
    'reservation.time': 'Time',
    'reservation.reservationFee': 'Reservation Fee',
    'reservation.feeDescription': 'This fee will be deducted from your bill',
    'reservation.proceedToPayment': 'Proceed to Payment',
    'reservation.payment': 'Payment',
    'reservation.paymentSummary': 'Payment Summary',
    'reservation.paymentMethod': 'Payment Method',
    'reservation.creditCard': 'Credit Card',
    'reservation.feeRefundInfo': 'Reservation Fee Information',
    'reservation.feeRefundDescription': 'The reservation fee will be deducted from your bill and refunded when you pay.',
    'reservation.payAndReserve': 'Pay & Reserve',
    
    // Reservations (Dashboard)
    'reservations.title': 'Reservation Management',
    'reservations.subtitle': 'Manage reservations and update their status',
    'reservations.totalReservations': 'Total Reservations',
    'reservations.pendingReservations': 'Pending Reservations',
    'reservations.confirmedReservations': 'Confirmed Reservations',
    'reservations.reservationRevenue': 'Reservation Revenue',
    'reservations.searchPlaceholder': 'Search by customer name, phone or table...',
    'reservations.allStatus': 'All Status',
    'reservations.pending': 'Pending',
    'reservations.confirmed': 'Confirmed',
    'reservations.completed': 'Completed',
    'reservations.cancelled': 'Cancelled',
    'reservations.noShow': 'No Show',
    'reservations.confirm': 'Confirm',
    'reservations.cancel': 'Cancel',
    'reservations.markCompleted': 'Mark Completed',
    'reservations.reservationDetails': 'Reservation Details',
    'reservations.customerName': 'Customer Name',
    'reservations.phone': 'Phone',
    'reservations.email': 'Email',
    'reservations.partySize': 'Party Size',
    'reservations.table': 'Table',
    'reservations.dateTime': 'Date & Time',
    'reservations.notes': 'Notes',
    'reservations.noReservations': 'No Reservations Found',
    'reservations.noReservationsMessage': 'There are no reservations for this date yet.',
    'orders.markServed': 'Mark Served',
    'orders.cancelOrder': 'Cancel Order',
    'orders.noOrders': 'No Orders Found',
    'orders.noOrdersMessage': 'There are no orders in this status yet.',
    
    // Campaigns
    'campaigns.title': 'Campaign Management',
    'campaigns.subtitle': 'Manage your discounts and promotions',
    'campaigns.addNew': 'Add New Campaign',
    'campaigns.activeCampaigns': 'Active Campaigns',
    'campaigns.thisMonthUsage': 'This Month Usage',
    'campaigns.totalDiscount': 'Total Discount',
    'campaigns.bogo': 'BUY 2 GET 1',
    'campaigns.validUntil': 'Valid Until:',
    'campaigns.campaignTitle': 'Campaign Title',
    'campaigns.titlePlaceholder': 'e.g., Weekend Discount',
    'campaigns.descriptionPlaceholder': 'Campaign details...',
    'campaigns.campaignType': 'Campaign Type',
    'campaigns.percentageDiscount': 'Percentage Discount',
    'campaigns.fixedDiscount': 'Fixed Discount',
    'campaigns.bogoFull': 'Buy 2 Get 1',
    'campaigns.typeSelect': 'Select type',
    'campaigns.discountAmount': 'Discount Amount',
    'campaigns.endDate': 'End Date',
    'campaigns.bannerUrl': 'Banner URL',
    
    // Loyalty
    'loyalty.title': 'Loyalty Program',
    'loyalty.subtitle': 'Create rewards to increase customer loyalty',
    'loyalty.programMembers': 'Program Members',
    'loyalty.thisMonthRewards': 'Rewards Used This Month',
    'loyalty.activeUsers': 'Active Users',
    'loyalty.programDetails': 'Loyalty program details',
    'loyalty.earnPoints': 'Earn {points} points for every ₺1 spent!',
    'loyalty.collectPoints': 'Collect your points and earn special rewards',
    'loyalty.rewards': 'Rewards',
    'loyalty.addReward': 'Add New Reward',
    'loyalty.points': 'Points',
    'loyalty.recentRedemptions': 'Recent Redemptions',
    'loyalty.last7Days': 'Last 7 days',
    'loyalty.rewardName': 'Reward Name',
    'loyalty.rewardNamePlaceholder': 'e.g., Free Dessert',
    'loyalty.rewardDescription': 'Reward details...',
    'loyalty.requiredPoints': 'Required Points',
    
    // Marketing
    'marketing.title': 'Marketing & Advertising',
    'marketing.subtitle': 'Manage shorts videos and banner ads',
    'marketing.shortsVideos': 'Shorts Videos',
    'marketing.totalViews': 'Total Views',
    'marketing.totalLikes': 'Total Likes',
    'marketing.bannerAds': 'Banner Ads',
    'marketing.addVideo': 'Add New Video',
    'marketing.addBanner': 'Add New Banner',
    'marketing.videoTitle': 'Video Title',
    'marketing.videoTitlePlaceholder': 'e.g., Our New Pizza Recipe',
    'marketing.videoUrl': 'Video URL',
    'marketing.thumbnailUrl': 'Thumbnail URL',
    'marketing.bannerTitle': 'Banner Title',
    'marketing.bannerTitlePlaceholder': 'e.g., Special Offer',
    'marketing.bannerImageUrl': 'Banner Image URL',
    
    // Settings
    'settings.title': 'Restaurant Settings',
    'settings.subtitle': 'Manage your restaurant information and features',
    'settings.basicInfo': 'Basic Information',
    'settings.restaurantName': 'Restaurant Name',
    'settings.cuisine': 'Cuisine Type',
    'settings.priceRange': 'Price Range',
    'settings.economical': '₺ - Economical',
    'settings.medium': '₺₺ - Medium',
    'settings.expensive': '₺₺₺ - Expensive',
    'settings.luxury': '₺₺₺₺ - Luxury',
    'settings.location': 'Location Information',
    'settings.address': 'Address',
    'settings.city': 'City',
    'settings.district': 'District',
    'settings.workingHours': 'Working Hours',
    'settings.openingTime': 'Opening Time',
    'settings.closingTime': 'Closing Time',
    'settings.features': 'Venue Features',
    'settings.featuresSubtitle': 'Select your restaurant features',
    'settings.saveChanges': 'Save Changes',
    'settings.preview': 'Preview',
    'settings.statistics': 'Statistics',
    'settings.totalReviews': 'Total Reviews',
    'settings.averageRating': 'Average Rating',
    'settings.menuItems': 'Menu Items',
    'settings.tableCount': 'Table Count',
    
    // Customer App - Explore
    'explore.search': 'Search for restaurant or cuisine...',
    'explore.featured': 'Area Stars',
    'explore.featuredBadge': 'Featured',
    'explore.allRestaurants': 'All Restaurants',
    'explore.tablesAvailable': 'tables available',
    'explore.capacity': 'capacity',
    'explore.avgTime': 'Avg. 15 min',
    
    // Customer App - Shorts
    'shorts.title': 'Shorts',
    'shorts.subtitle': 'Special content and campaigns from restaurants',
    'shorts.restaurant': 'Restaurant',
    'shorts.noComments': 'No comments yet',
    
    // Customer App - Restaurant Detail
    'restaurant.notFound': 'Restaurant not found',
    'restaurant.menu': 'Menu',
    'restaurant.reviews': 'Reviews',
    'restaurant.campaigns': 'Campaigns',
    'restaurant.info': 'Information',
    'restaurant.workingHours': 'Working Hours',
    'restaurant.loyaltyProgram': 'Loyalty Program',
    'restaurant.earnPerLira': '{points} points per ₺1',
    'restaurant.joinProgram': 'Join Program',
    'restaurant.takeaway': 'Place Takeaway Order',
    'restaurant.makeReservation': 'Make Reservation',
    'restaurant.ambiance': 'Ambiance:',
    'restaurant.hygiene': 'Hygiene:',
    'restaurant.service': 'Service:',
    
    // Customer App - Takeaway
    'takeaway.title': 'Takeaway Order',
    'takeaway.subtitle': 'Place your order and pick it up at the restaurant',
    'takeaway.selectRestaurant': 'Select Restaurant',
    'takeaway.myCart': 'My Cart',
    'takeaway.emptyCart': 'Your cart is empty',
    'takeaway.backToMenu': 'Back to Menu',
    'takeaway.addToCart': 'Add',
    'takeaway.yourOrder': 'Your Order',
    'takeaway.orderNote': 'Order Note (Optional)',
    'takeaway.notePlaceholder': 'e.g., I want a lightly cooked pizza',
    'takeaway.paymentSummary': 'Payment Summary',
    'takeaway.serviceFee': 'Service Fee (10%)',
    'takeaway.proceedToPayment': 'Proceed to Payment',
    'takeaway.completeOrder': 'Complete Order',
    'takeaway.orderReceived': 'Order Received!',
    'takeaway.orderReceivedMessage': 'Your Order Has Been Received!',
    'takeaway.orderNumber': 'Your order number: #{number}',
    'takeaway.pickupMessage': 'Your order is being prepared. Please come to the restaurant within 15-20 minutes and show your receipt number to pick up your order.',
    'takeaway.orderSummary': 'Order Summary',
    'takeaway.restaurant': 'Restaurant:',
    'takeaway.estimatedTime': 'Estimated Preparation Time: 15-20 minutes',
    'takeaway.confirmOrder': 'Confirm Order',
    
    // Customer App - Profile
    'profile.memberSince': 'Member Since: {year}',
    'profile.editProfile': 'Edit Profile',
    'profile.stats': 'Statistics',
    'profile.totalOrders': 'Total Orders',
    'profile.favoriteRestaurants': 'Favorite Restaurants',
    'profile.reviewCount': 'Review Count',
    'profile.totalPoints': 'Total Points',
    'profile.loyaltyPrograms': 'Loyalty Programs',
    'profile.pointStatus': 'Your point status',
    'profile.recentOrders': 'Recent Orders',
    'profile.orderHistory': 'Your order history',
    'profile.viewAllOrders': 'View All Orders',
    'profile.myReviews': 'My Reviews',
    'profile.reviewsSubtitle': 'Your reviews',
    
    // QR Menu
    'qr.digitalMenu': 'Digital Menu',
    'qr.callWaiter': 'Call Waiter',
    'qr.cart': 'Cart',
    'qr.popularItems': 'Popular Items',
    'qr.preparation': 'Preparation',
    'qr.ingredients': 'Ingredients',
    'qr.allergenWarning': 'Allergen Warning',
    'qr.watchVideo': 'Watch Preparation Video',
    'qr.addToCart': 'Add to Cart',
    'qr.notInStock': 'Out of Stock',
    'qr.waiterCalled': 'Waiter called',
    'qr.goToCart': 'Go to Cart',
    'qr.items': 'Items',
    'qr.myCart': 'My Cart',
    'qr.payment': 'Payment',
    'qr.paymentMethod': 'Payment Method',
    'qr.creditCard': 'Credit/Debit Card',
    'qr.cash': 'Cash',
    'qr.tip': 'Tip',
    'qr.noTip': 'None',
    'qr.tipAmount': 'Tip amount:',
    'qr.pay': 'Pay',
    'qr.processing': 'Processing...',
    'qr.cashPaymentNote': 'Cash Payment: Please inform your waiter that you would like to pay in cash.',
    'qr.paymentSuccess': 'Payment Successful!',
    'qr.thankYou': 'Thank you for your order',
    'qr.orderNumber': 'Order No',
    'qr.date': 'Date',
    'qr.time': 'Time',
    'qr.product': 'Product',
    'qr.quantity': 'Qty',
    'qr.paymentMethodInfo': 'Payment Method',
    'qr.creditCardLast4': 'Credit Card (**** {last4})',
    'qr.downloadReceipt': 'Download Receipt',
    'qr.rateExperience': 'Rate Your Experience',
    'qr.thankYouNote': 'Hope to see you again, enjoy your meal! 🍽️',
    'qr.shareExperience': 'Share Your Experience',
    'qr.overallRating': 'Overall Rating',
    'qr.excellent': 'Excellent! 🌟',
    'qr.veryGood': 'Very Good! 👍',
    'qr.good': 'Good 😊',
    'qr.average': 'Average 😐',
    'qr.poor': 'Poor 😞',
    'qr.detailedRating': 'Detailed Rating',
    'qr.ambiance': 'Ambiance',
    'qr.hygiene': 'Hygiene',
    'qr.service': 'Service',
    'qr.foodRating': 'Food Rating',
    'qr.yourComment': 'Your Comment (Optional)',
    'qr.commentPlaceholder': 'Share your experience with us...',
    'qr.submitReview': 'Submit Review',
    'qr.notNow': 'Not Now',
    'qr.reviewThanks': 'Thank You!',
    'qr.reviewSaved': 'Your review has been saved',
    'qr.reservationFeeDeduction': 'Reservation Fee Deduction',
    'qr.reservationFeeInfo': 'Reservation Fee Information',
    'qr.reservationFeeDescription': 'Your reservation fee has been deducted from your bill.',
    'qr.table': 'Table',
    'qr.persons': 'Persons',
    'qr.item': 'Item',
    'qr.serviceFee': 'Service Fee',
    'qr.paymentSummary': 'Payment Summary',
    'qr.cashPayment': 'Cash Payment',
    'qr.share': 'Share',
    'qr.paymentSuccessful': 'Payment Successful',
    'qr.thankYouForOrder': 'Thank you for your order',
    'qr.backToMenu': 'Back to Menu',
    'qr.openDemoMenu': 'Open Demo Menu',
    'qr.scanQR': 'Scan the QR code on your table',
    'qr.howToUse': 'How to Use?',
    'qr.step1': 'Scan the QR code on your table with your phone camera',
    'qr.step2': 'Browse our digital menu and place your order',
    'qr.step3': 'Complete payment and enjoy your meal',
    'qr.demoMode': 'Demo Mode',
    'qr.demoDesc': 'You can open the demo menu to test the application',
    'qr.scanIssue': 'Having trouble scanning the QR code? Please ask our staff for help.',
    'qr.emptyCart': 'Your cart is empty',
    'qr.yourOrder': 'Your Order',
    'qr.proceedToPayment': 'Proceed to Payment',
    'qr.calories': 'Calories',
    'qr.min': 'min',
    'qr.outOfStock': 'Out of Stock',
    'qr.orderNotes': 'Order Notes',
    'qr.orderNotesPlaceholder': 'You can write your special requests here...',
    'qr.all': 'All',
    'qr.goToCartWith': 'Go to Cart',
    'qr.vegan': 'Vegan',
    'qr.vegetarian': 'Vegetarian',
    'qr.glutenFree': 'Gluten Free',
    
    // Home Page
    'home.restaurant': 'Restaurants',
    'home.happyCustomer': 'Happy Customers',
    'home.avgRating': 'Average Rating',
    'home.orders': 'Orders',
    'home.cuisineTurkish': 'Turkish Cuisine',
    'home.cuisineItalian': 'Italian',
    'home.cuisineJapanese': 'Japanese',
    'home.cuisineChinese': 'Chinese',
    'home.cuisineMexican': 'Mexican',
    'home.cuisineIndian': 'Indian',
    'home.popularCategories': 'Popular Categories',
    'home.whyChefPoint': 'Why Chef Point?',
    'home.popularRestaurants': 'Popular Restaurants',
    'home.trendingRestaurants': 'Trending Restaurants',
    'home.viewAll': 'View All',
    'home.startExploring': 'Start Exploring Now!',
    'home.exploreDescription': 'Find the best restaurant for you among thousands and order instantly.',
    'home.explore': 'Explore →',
    'home.reviews': 'reviews',
    'home.deliveryTime': 'min',
    'home.popular': 'Popular',
    'home.new': 'New',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.reviews': 'Reviews',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'tr') ? saved : 'tr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const translation = translations[language][key];
    if (!translation) {
      console.warn(`Translation missing for key: ${key}`);
      return key;
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
